### ISSUE TITLE
Email sending is broken

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#584]
Not great to lose monitoring on community content... last email was on Nov 19th, looks like there was a deploy on the 21st that probably included the breaking change (most recent deploy before that was on Nov 1st)

Screenshot of Heroku deploys:
<img width="532" alt="screen shot 2018-12-08 at 5 22 23 pm" src="https://user-images.githubusercontent.com/775657/49691346-fa763e80-fb0d-11e8-8d0b-1056b2e7d2f9.png">

**Comment by toddmedema** [comment]
Notes from attempting to debug:

1. Here's the error that happens when you call `mail.send` on local or prod:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getSocket' of undefined
    at sendMail (/Users/todd/code/expedition/services/api/dist/server.js:190161:25)
    at /Users/todd/code/expedition/services/api/dist/server.js:190649:9
    at new Promise (<anonymous>)
    at new F (/Users/todd/code/expedition/services/api/dist/server.js:26077:28)
    at Object.send (/Users/todd/code/expedition/services/api/dist/server.js:190648:12)
    at mailNewQuestToAdmin (/Users/todd/code/expedition/services/api/dist/server.js:109609:17)
    at /Users/todd/code/expedition/services/api/dist/server.js:109634:13
    at tryCatcher (/Users/todd/code/expedition/services/api/dist/server.js:22662:23)
    at Promise._settlePromiseFromHandler (/Users/todd/code/expedition/services/api/dist/server.js:154041:31)
    at Promise._settlePromise (/Users/todd/code/expedition/services/api/dist/server.js:154098:18)
    at Promise._settlePromise0 (/Users/todd/code/expedition/services/api/dist/server.js:154143:10)
    at Promise._settlePromises (/Users/todd/code/expedition/services/api/dist/server.js:154222:18)
    at Async._drainQueue (/Users/todd/code/expedition/services/api/dist/server.js:153494:16)
    at Async._drainQueues (/Users/todd/code/expedition/services/api/dist/server.js:153504:10)
    at Immediate.Async.drainQueues (/Users/todd/code/expedition/services/api/dist/server.js:153378:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
(node:40153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

2. Running the code on boot had the same error:

```
setTimeout(() => {
  const foo = new Promise((resolve, reject) => {
    transporter.sendMail(opts, (err: Error, data: any) => {
      console.log('done!');
      if (err) {
        reject(err);
      } else {
        resolve(data);
      }
    });
  });
}, 60 * 1000);
```

3. Updating `nodemailer` to the latest version did not help
